/**
 * @fileoverview Generated by react-mvi cli.
 */

import * as React from 'react';
import {
  render
} from 'react-dom';
import {
  Provider
} from '@react-mvi/core';
import {
  AppComponent
} from './views/app';
import {
  AppIntent
} from './intents/intent';
import {
  AppStore
} from './stores/store';



render(
  <Provider intent={AppIntent} store={AppStore}>
    <AppComponent/>
  </Provider>,
  document.querySelector('.app')
);

