# Class Injector
The main class.
## Index### Constructors* [constructor](_di_injector_.injector.html#constructor)### Properties* [bindings](_di_injector_.injector.html#bindings)* [intercepts](_di_injector_.injector.html#intercepts)* [parent](_di_injector_.injector.html#parent)* [templateDefinitions](_di_injector_.injector.html#templatedefinitions)* [templates](_di_injector_.injector.html#templates)### Methods* [applyInterceptor](_di_injector_.injector.html#applyinterceptor)* [createArguments](_di_injector_.injector.html#createarguments)* [createChildInjector](_di_injector_.injector.html#createchildinjector)* [doCreate](_di_injector_.injector.html#docreate)* [findOnParent](_di_injector_.injector.html#findonparent)* [fromParams](_di_injector_.injector.html#fromparams)* [get](_di_injector_.injector.html#get)* [getInstance](_di_injector_.injector.html#getinstance)* [getInstanceFromSelf](_di_injector_.injector.html#getinstancefromself)* [getInterceptorInstance](_di_injector_.injector.html#getinterceptorinstance)* [getMethodProxy](_di_injector_.injector.html#getmethodproxy)* [initialize](_di_injector_.injector.html#initialize)* [inject](_di_injector_.injector.html#inject)* [injectOnce](_di_injector_.injector.html#injectonce)* [injectToInstance](_di_injector_.injector.html#injecttoinstance)* [instantiateEagerSingletons](_di_injector_.injector.html#instantiateeagersingletons)* [invokeNewCall](_di_injector_.injector.html#invokenewcall)* [keys](_di_injector_.injector.html#keys)* [selfKeys](_di_injector_.injector.html#selfkeys)## Constructors### new Injector(modules: [Module](../interfaces/_di_module_.module.html)[]): [Injector](_di_injector_.injector.html)  * Defined in [di/injector.tsx:159](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L159)#### Parameters| Name | Type | Description || ---- | ---- | ---- || modules | [Module](../interfaces/_di_module_.module.html)[]| The module array that is defined dependencies. |#### Returns: [Injector](_di_injector_.injector.html)## Properties### Private bindings: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)
Definition of bindings.* Defined in [di/injector.tsx:144](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L144)### Private intercepts: [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)[]
Definition of interceptor bindings.* Defined in [di/injector.tsx:149](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L149)### Private parent: [Injector](_di_injector_.injector.html)
Parent `Injector`.* Defined in [di/injector.tsx:139](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L139)### Private templateDefinitions: [key: string]: any
Definition of template.* Defined in [di/injector.tsx:159](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L159)### Private templates: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)
Definition of template bindings.* Defined in [di/injector.tsx:154](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L154)## Methods### Private applyInterceptor<T>(inst: T): voidHook interceptor.  * Defined in [di/injector.tsx:590](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L590)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || inst | T|  |#### Returns: void### Private createArguments<T>(injections: [Injections](_di_injector_.injections.html)<T>, params: any, useKeys?: boolean): any[] | Create arguments from bindings.  * Defined in [di/injector.tsx:440](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L440)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || injections | [Injections](_di_injector_.injections.html)<T>| Dependencies. || params | any|  || useKeys? | boolean|  |#### Returns: any[] | Array of dependencies.
			### createChildInjector(modules: [Module](../interfaces/_di_module_.module.html)[]): [Injector](_di_injector_.injector.html)Create child injector.Child injector is binded parent modules and self modules.  * Defined in [di/injector.tsx:290](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L290)#### Parameters| Name | Type | Description || ---- | ---- | ---- || modules | [Module](../interfaces/_di_module_.module.html)[]| The new module to add. |#### Returns: [Injector](_di_injector_.injector.html)### Private doCreate<T>(ctor: [ClassType](../interfaces/_di_classtype_.classtype.html)<T>, injections: [Injections](_di_injector_.injections.html)<T>, params: any): TCreate instance and resolve bindings.  * Defined in [di/injector.tsx:365](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L365)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || ctor | [ClassType](../interfaces/_di_classtype_.classtype.html)<T>| Constructor function. || injections | [Injections](_di_injector_.injections.html)<T>| Dependencies. || params | any|  |#### Returns: TThe instance that dependencies injected.
								### Private findOnParent(cb: Function): voidSearch include parents `Injector`.Until passed callback return true, traverse parents.  * Defined in [di/injector.tsx:508](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L508)#### Parameters| Name | Type | Description || ---- | ---- | ---- || cb | Function| Callback function. |#### Returns: void### Private fromParams(val: any): [Binding](../interfaces/_di_binding_.binding.html)Create binding from additional parameter.  * Defined in [di/injector.tsx:525](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L525)#### Parameters| Name | Type | Description || ---- | ---- | ---- || val | any| defined value in Binding. |#### Returns: [Binding](../interfaces/_di_binding_.binding.html)Binding definition.
								### get(key: string | RegExp): anyGet instance from self and parents.  * Defined in [di/injector.tsx:302](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L302)#### Parameters| Name | Type | Description || ---- | ---- | ---- || key | string | RegExp| The key of dependency. |#### Returns: anyThe instance that created from found dependency.
								### Private getInstance<T>(bindingName: string, dynamicName: string, item: [Binding](../interfaces/_di_binding_.binding.html), isTemplate: boolean): anyCreate dependent instance.  * Defined in [di/injector.tsx:543](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L543)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || bindingName | string| Instance name. || dynamicName | string|  || item | [Binding](../interfaces/_di_binding_.binding.html)| The defitnition of dependencies. || isTemplate | boolean|  |#### Returns: anyThe instance that is constructed.
									### getInstanceFromSelf(key: string | RegExp): anyGet instance from self, not includes parents.  * Defined in [di/injector.tsx:317](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L317)#### Parameters| Name | Type | Description || ---- | ---- | ---- || key | string | RegExp| The key of dependency. |#### Returns: anyThe instance that created from found dependency.
									### Private getInterceptorInstance(i: any): [MethodProxy](../interfaces/_di_method_proxy_.methodproxy.html)Get interceptor instance.  * Defined in [di/injector.tsx:627](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L627)#### Parameters| Name | Type | Description || ---- | ---- | ---- || i | any| Interceptor class. |#### Returns: [MethodProxy](../interfaces/_di_method_proxy_.methodproxy.html)INterceptor instance.
									### Private getMethodProxy(context: any, base: Function, interceptor: [MethodProxy](../interfaces/_di_method_proxy_.methodproxy.html), propertyKey: string): (...args: any[])=> anyReturn wrapped method by interceptor.  * Defined in [di/injector.tsx:643](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L643)#### Parameters| Name | Type | Description || ---- | ---- | ---- || context | any| Execution context. || base | Function| Real method. || interceptor | [MethodProxy](../interfaces/_di_method_proxy_.methodproxy.html)| Instance of interceptor. || propertyKey | string| Property name. |#### Returns: (...args: any[])=> anyWrapped function.
									### Private initialize(modules: [Module](../interfaces/_di_module_.module.html)[]): voidIniaitlize modules and injector.  * Defined in [di/injector.tsx:173](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L173)#### Parameters| Name | Type | Description || ---- | ---- | ---- || modules | [Module](../interfaces/_di_module_.module.html)[]| The `Module` that are defined dependency relations. |#### Returns: void### inject<T>(ctor: [ClassType](../interfaces/_di_classtype_.classtype.html)<T>, params?: any): TConstruct dependency resolved instance. example
											class Foo {...}
											class Bar {
											@inject()
											private foo
											constructor() {}
											}
											class TestModule extends AbstractModule {
											public configure() {
											this.bind('foo').to(Foo);
											}
											}
											var injector = new Injector([new TestModule()]);
											//This call inject foo property of class Bar to module defined value.
											injector.inject<Bar>(Bar);
												* Defined in [di/injector.tsx:227](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L227)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || ctor | [ClassType](../interfaces/_di_classtype_.classtype.html)<T>| Constructor function || params? | any| Additional dependencies. |#### Returns: TDependency resolved instance.### injectOnce<T>(ctor: [ClassType](../interfaces/_di_classtype_.classtype.html)<T>, params?: any): TResolve dependencies at once.If passed same constructor function twice,return first time instantiated instance.  * Defined in [di/injector.tsx:277](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L277)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || ctor | [ClassType](../interfaces/_di_classtype_.classtype.html)<T>| Constructor function. || params? | any| Additional dependencies. |#### Returns: T### injectToInstance<T>(inst: T, params?: any): TInject dependency to instance. example
																	class Foo {...}
																	class Bar {
																	@inject()
																	private foo
																	constructor() {}
																	}
																	class TestModule extends AbstractModule {
																	public configure() {
																	this.bind('foo').to(Foo);
																	}
																	}
																	var injector = new Injector([new TestModule()]);
																	//This call inject foo property of class Bar to module defined value.
																	injector.injectToInstance<Bar>(new Bar());
																		* Defined in [di/injector.tsx:261](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L261)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || inst | T| Instance. || params? | any| Additional dependencies. |#### Returns: TDependency injected instance.### Private instantiateEagerSingletons(): voidInstantiate eagerSingleton class.  * Defined in [di/injector.tsx:190](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L190)#### Returns: void### Private invokeNewCall<T>(ctor: any, args: any[]): TInstantiate class.To fast instantiation, not use Function.prototype.apply but use switch case.  * Defined in [di/injector.tsx:389](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L389)#### Type parameters* #### T#### Parameters| Name | Type | Description || ---- | ---- | ---- || ctor | any| Constructor function. || args | any[]| Arguments. |#### Returns: TThe instance that dependencies injected.
																			### keys(): string[]  * Defined in [di/injector.tsx:349](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L349)#### Returns: string[]all registerd dependent names.### selfKeys(): string[]Return all registered dependent names of self, not includes parents.  * Defined in [di/injector.tsx:340](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/injector.tsx#L340)#### Returns: string[]List of dependent names.
																			Generated using [TypeDoc](http://typedoc.io)