# Class AbstractModule
Base implementation of `Module`.### Implements* [Module](../interfaces/_di_module_.module.html)
## Index### Properties* [bindings](_di_abstract_module_.abstractmodule.html#bindings)* [intercepts](_di_abstract_module_.abstractmodule.html#intercepts)* [templates](_di_abstract_module_.abstractmodule.html#templates)### Methods* [bind](_di_abstract_module_.abstractmodule.html#bind)* [bindInterceptor](_di_abstract_module_.abstractmodule.html#bindinterceptor)* [configure](_di_abstract_module_.abstractmodule.html#configure)* [getBindings](_di_abstract_module_.abstractmodule.html#getbindings)* [getIntercepts](_di_abstract_module_.abstractmodule.html#getintercepts)* [getTemplates](_di_abstract_module_.abstractmodule.html#gettemplates)* [mixin](_di_abstract_module_.abstractmodule.html#mixin)* [template](_di_abstract_module_.abstractmodule.html#template)## Properties### Private bindings: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)
Map of bindings.* Defined in [di/abstract-module.tsx:42](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L42)### Private intercepts: [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)[]
Map of interceptor.* Defined in [di/abstract-module.tsx:52](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L52)### Private templates: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)
Map of template.* Defined in [di/abstract-module.tsx:47](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L47)## Methods### bind(name: string): [BindingPlaceholder](_di_binding_.bindingplaceholder.html)Define binding id.  * Defined in [di/abstract-module.tsx:60](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L60)#### Parameters| Name | Type | Description || ---- | ---- | ---- || name | string| Binding id. |#### Returns: [BindingPlaceholder](_di_binding_.bindingplaceholder.html)Concrete class.
### bindInterceptor(targetSymbol: symbol): [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)Register interceptor Symbol.  * Defined in [di/abstract-module.tsx:78](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L78)#### Parameters| Name | Type | Description || ---- | ---- | ---- || targetSymbol | symbol| Symbol that set interceptor target. |#### Returns: [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)### configure(): voidConfigure binding of modules. override
* Implementation of [Module](../interfaces/_di_module_.module.html).[configure](../interfaces/_di_module_.module.html#configure)* Defined in [di/abstract-module.tsx:116](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L116)#### Returns: void### getBindings(): [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)Return binding map.  * Implementation of [Module](../interfaces/_di_module_.module.html).[getBindings](../interfaces/_di_module_.module.html#getbindings)* Defined in [di/abstract-module.tsx:89](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L89)#### Returns: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)Binding definitions.
### getIntercepts(): [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)[]Get list of symbol that interceptor target.  * Implementation of [Module](../interfaces/_di_module_.module.html).[getIntercepts](../interfaces/_di_module_.module.html#getintercepts)* Defined in [di/abstract-module.tsx:107](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L107)#### Returns: [InterceptPlaceholder](_di_binding_.interceptplaceholder.html)[]Definition of binding of interceptor.
### getTemplates(): [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)Return template map.  * Implementation of [Module](../interfaces/_di_module_.module.html).[getTemplates](../interfaces/_di_module_.module.html#gettemplates)* Defined in [di/abstract-module.tsx:98](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L98)#### Returns: [BindingRelation](../interfaces/_di_binding_.bindingrelation.html)Template definitions.
### mixin(m: [AbstractModule](_di_abstract_module_.abstractmodule.html)): voidMixin other module configs.  * Defined in [di/abstract-module.tsx:123](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L123)#### Parameters| Name | Type | Description || ---- | ---- | ---- || m | [AbstractModule](_di_abstract_module_.abstractmodule.html)| Module. |#### Returns: void### template(name: string): [TemplatePlaceholder](_di_binding_.templateplaceholder.html)Define template id.  * Defined in [di/abstract-module.tsx:69](https://github.com/brn/react-mvi/blob/master/modules/core/src/di/abstract-module.tsx#L69)#### Parameters| Name | Type | Description || ---- | ---- | ---- || name | string| Template binding id. |#### Returns: [TemplatePlaceholder](_di_binding_.templateplaceholder.html)
Generated using [TypeDoc](http://typedoc.io)