/**
 * @fileoverview Generated by react-mvi cli.
 */


import * as React from 'react';
import {
  connect
} from '@react-mvi/core';


export const AppComponent = connect({
  mapIntentToProps(intent) {
    return {
      onMount: intent.callback('app::mounted')
    }
  }
})(class AppComponent extends React.Component<{onMount(): void}, {}> {
  public render() {
    return (
      <div>Hello World!</div>
    );
  }


  public componentDidMount() {
    this.props.onMount();
  }
});
