/**
 * @fileoverview Generated by react-mvi cli.
 */


import {
  store,
  Store
} from '@react-mvi/core';
import {
  Observable
} from 'rxjs/Rx';
import {
  AppIntent
} from '../intents/intent';


@store
export class AppStore implements Store<{view: {greeting: Observable<string>}}> {
  private intent: AppIntent;

  public initialize() {
    return {
      view: {
        greeting: this.intent.onMounted.mapTo('Hello World!').startWith('')
      }
    };
  }
}
